Merge uat into main (#23)
Co-authored-by: SimoneMiccoli1 <146010879+SimoneMiccoli1@users.noreply.github.com>
Co-authored-by: SMANUM <125576365+SMANUM@users.noreply.github.com>
Co-authored-by: Simone Munao <simone.munao@nttdata.com>
Co-authored-by: GitHub Action <action@github.com>
Co-authored-by: SimoneMiccoli1 <simone.miccoli@aurigaspa.com>
Co-authored-by: pasquales <pasqualesansonna@aurigaspa.com>

diff --git a/.github/workflows/manual-create-pre-release-from-dev.yml b/.github/workflows/manual-create-pre-release-from-dev.yml
--- a/.github/workflows/manual-create-pre-release-from-dev.yml
+++ b/.github/workflows/manual-create-pre-release-from-dev.yml
@@ -3,13 +3,6 @@ name: Manual create pre-release from dev
 on:
   workflow_dispatch:
     inputs:
-      env:
-        description: 'Environment:'
-        type: choice
-        required: true
-        default: dev
-        options:
-        - dev
       commit:
         description: 'Pre-release type:'
         type: choice
@@ -18,7 +11,8 @@ on:
         options:
         - feat
         - fix
- 
+        - major
+        
 defaults:
   run:
     shell: bash
@@ -30,7 +24,7 @@ jobs:
     if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/dev'
     strategy:
       matrix:
-        environment: ["${{ inputs.env }}"]
+        environment: [dev]
 
     name: "manual-create-pre-release"
     runs-on: ubuntu-latest
@@ -49,6 +43,62 @@ jobs:
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Setup JDK
+        uses: graalvm/setup-graalvm@v1
+        with:
+          java-version: '17'
+          distribution: 'graalvm'
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Test and Integration tests
+        run: |
+          mvn test -Dquarkus.package.type=native -Dquarkus.application.name=atm-layer-wf-task -Dquarkus.profile=prod
+
+      - name: Create Status check based on postman results
+        id: process-postman
+        uses: im-open/process-postman-test-results@v2.1.5
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          results-file: src/test/resources/integration-test/output/result.json
+          report-name: 'Postman build: ${{ github.run_number }}'
+          create-status-check: true
+          create-pr-comment: true
+          update-comment-if-one-exists: true
+          ignore-test-failures: true
+          timezone: 'europe/rome'
+
+      - name: Fail if there were errors in the postman tests
+        if: steps.process-postman.outputs.test-outcome == 'Failed'
+        run: |
+          echo "There were postman failures."
+          exit 1
+
+      - name: Upload result.html
+        uses: actions/upload-artifact@v3
+        with:
+          name: html-report
+          path: src/test/resources/integration-test/output/result.html
+
+      - name: JaCoCo Code Coverage Report
+        id: jacoco_reporter
+        uses: PavanMudigonda/jacoco-reporter@v4.9
+        with:
+          coverage_results_path: target/jacoco-report/jacoco.xml
+          coverage_report_name: 'Coverage create pre-release: ${{ github.run_number }}'
+          coverage_report_title: JaCoCo
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          skip_check_run: false
+          minimum_coverage: 90
+          fail_below_threshold: false
+          publish_only_summary: false
+
+      - name: Fail Build if overall coverage is less than 90%
+        if: steps.jacoco_reporter.outputs.coverage_percentage < 90.0 
+        uses: actions/github-script@v6
+        with:
+          script: |
+            core.setFailed('Overall coverage is less than 90%!')
 
       - name: Build docker image
         env:
